background_opacity 0.85

font_family "JetBrainsMono Nerd Font"
font_size 13

cursor_shape beam
cursor_trail 1

window_margin 30

confirm_os_window_close 0

# theme 

# Tokyo Night (night) color scheme
background #1a1b26
foreground #c0caf5
selection_background #364a82
selection_foreground #c0caf5

# cursor
cursor #c0caf5
cursor_text_color #1a1b26

# normal colors
color0 #15161e
color1 #f7768e
color2 #9ece6a
color3 #e0af68
color4 #7aa2f7
color5 #bb9af7
color6 #7dcfff
color7 #a9b1d6

# bright colors
color8 #414868
color9 #f7768e
color10 #9ece6a
color11 #e0af68
color12 #7aa2f7
color13 #bb9af7
color14 #7dcfff
color15 #c0caf5

# tab bar
active_tab_background   #1f2335
active_tab_foreground   #c0caf5
inactive_tab_background #15161e
inactive_tab_foreground #787c99
tab_bar_background      #1a1b26


